# Generated by Django 4.2.16 on 2024-12-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customer_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
