# Generated by Django 4.2.16 on 2024-12-04 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_forecast', models.PositiveIntegerField(blank=True, null=True)),
                ('optimized_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_optimization', to='products.product')),
            ],
        ),
    ]
