# Generated by Django 4.2.16 on 2024-12-04 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingoptimization',
            name='customer_rating',
        ),
    ]
